/*
 *   IRC - Internet Relay Chat, ircd/version.c
 *   Copyright (C) 1990 Chelsea Ashley Dyerman
 *
 *   This program is free software; you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation; either version 1, or (at your option)
 *   any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with this program; if not, write to the Free Software
 *   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 */

/*
 * This file is generated by mkversion.sh. Any changes made will go away.
 */

#include "struct.h"
#include "patchlevel.h"

char *generation = "2";
char *creation = "Thu May 10 DST at 14:14:04 EET";
char *version = PATCHLEVEL;

char *infotext[] =
    {
	"Based on the original code written by Jarkko Oikarinen",
	"Copyright 1988,1989 University of Oulu, Computing Center",
	"",
	"This program is free software; you can redistribute it and/or",
	"modify it under the terms of the GNU General Public License as",
	"published by the Free Software Foundation; either version 1, or",
	"(at your option) any later version.",
	"",
	"The following persons have made many changes and enhancements to the",
	"code and may know how IRC really works if you have questions about it:",
	"",
	"WiZ          Jarkko Oikarinen         jto@tolsun.oulu.fi",
	"Msa          Markku Savela            Markku.Savela@vtt.fi",
	"Misha        Mike Bolotski            mikeb@salmon.ee.ubc.ca",
	"Chelsea      Chelsea Ashley Dyerman   casie@earth.CChem.Berkeley.EDU",
	"Wumpus       Greg Lindahl             gl8f@astsun.astro.virginia.edu",
	"",
	"Those who helped in prior versions and continue to be helpful:",
	"",
	"             Markku Jarvinen          mta@tut.fi",
	"             Kimmo Suominen           kim@kannel.lut.fi",
	"             Jeff Trim                jtrim@orion.cair.du.edu",
	"Vijay        Vijay Subramaniam        vijay@lll-winken.llnl.gov",
	"             Karl Kleinpaste          karl@cis.ohio-state.edu",
	"Wisner       Bill Wisner              wisner@hayes.fai.alaska.edu",
	"             Tom Davis                conslt16@zeus.unl.edu",
	"",
	"Various modifications, bugreports, cleanups by:",
	"",
	"             Hugo Calendar            hugo@!ucscl.ucsc.edu",
	"             Bo Adler                 beau@through.cs.caltech.edu",
	"BigCheese    Michael Sandrof          ms5n+@andrew.cmu.edu",
	"             Jon Solomon              jsol@buit5.bu.edu",
	"             Jan Peterson             jlp@hamblin.byu.edu",
	"",
	"Alpha and beta testers, who put up with our bugs, and such:",
	"",
	"Trillian     Helen Rose               hrose@uceng.uc.edu",
	"",
	"Thanks also goes to those persons not mentioned here who have added",
	"their advice, opinions, and code to IRC.",
	0,
    };

