#!/bin/sh
eval "1>/dev/null"
eval "2>1"
/bin/cp hash.c hash.c.temp
/bin/cp hash.c hash.c.old
csum=`sum s_bsd.c`
sed -e "s/SBSDC/[${csum}]/g" hash.c.temp > hash.c
/bin/mv -f hash.c hash.c.temp
csum=`sum channel.c`
sed -e "s/CHANC/[$csum]/g" hash.c.temp > hash.c
/bin/mv -f hash.c hash.c.temp
csum=`sum ircd.c`
sed -e "s/IRCDC/[$csum]/g" hash.c.temp > hash.c
/bin/mv -f hash.c hash.c.temp
csum=`sum s_misc.c`
sed -e "s/SMISC/[$csum]/g" hash.c.temp > hash.c
/bin/mv -f hash.c hash.c.temp
csum=`sum hash.c.old`
sed -e "s/HASHC/[$csum]/g" hash.c.temp > hash.c
/bin/mv -f hash.c hash.c.temp
csum=`sum version.c.SH`
sed -e "s/VERSH/[$csum]/g" hash.c.temp > hash.c
/bin/mv -f hash.c hash.c.temp
csum=`sum s_bsd.c`
sed -e "s/MAKEF/[$csum]/g" hash.c.temp > hash.c
/bin/rm -f hash.c.temp
